/*
 * ConfigurazioneAmbienteJDialog.java
 *
 * Created on 24 febbraio 2008, 14.59
 */

package gui.dialog;

import javax.swing.SpinnerListModel;
import gui.SiGeMv2App;

/**
 *
 * @author  Jordy
 */
public class ConfigurazioneAmbienteJDialog extends javax.swing.JDialog {
    private static final int DIMPROCESSI = 20;
    private static final int DIMRAM = 9;
    private static final int DIMSWAP = 7;
    private static final int DIMPAGINE = 3;
    
    private int numProcessi;
    private int dimensioneRAM;
    private int dimensioneAreaSWAP;
    private int dimensionePagina;
    private int tempoContextSwitch;
    private int tempoAccessoDisco;
    private int bandaBusDati;
    

    /** Creates new form ConfigurazioneAmbienteJDialog */
    public ConfigurazioneAmbienteJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initJSpinnerProcessi();
        initSpinnerDimensioneRAM();
        initSpinnerDimensioneSWAP();
        initSpinnerPagine();
        initSpinnerTempi();
    }
    
    public ConfigurazioneAmbienteJDialog(ConfigurazioneAmbienteJDialog conf) {
        setNumProcessi(conf.getNumProcessi());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitoloConfigurazioneAmbiente = new javax.swing.JLabel();
        jLabelDimensioneRAM = new javax.swing.JLabel();
        jLabelDimensioneSWAP = new javax.swing.JLabel();
        jLabelTempoContextSwitch = new javax.swing.JLabel();
        jLabelTempoAccessoDisco = new javax.swing.JLabel();
        jLabelBandaBusDati = new javax.swing.JLabel();
        jLabelNumProcessi = new javax.swing.JLabel();
        jButtonAvanti = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();
        jSpinnerProcessi = new javax.swing.JSpinner();
        jLabelDimensionePagina = new javax.swing.JLabel();
        jSpinnerTempoContextSwitch = new javax.swing.JSpinner();
        jSpinnerTempoAccessoDisco = new javax.swing.JSpinner();
        jSpinnerBandaBusDati = new javax.swing.JSpinner();
        jSpinnerDimensioneRAM = new javax.swing.JSpinner();
        jSpinnerDimensioneAreaSWAP = new javax.swing.JSpinner();
        jSpinnerDimensionePagina = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gui.SiGeMv2App.class).getContext().getResourceMap(ConfigurazioneAmbienteJDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabelTitoloConfigurazioneAmbiente.setFont(resourceMap.getFont("jLabelTitoloConfigurazioneAmbiente.font")); // NOI18N
        jLabelTitoloConfigurazioneAmbiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitoloConfigurazioneAmbiente.setText(resourceMap.getString("jLabelTitoloConfigurazioneAmbiente.text")); // NOI18N
        jLabelTitoloConfigurazioneAmbiente.setName("jLabelTitoloConfigurazioneAmbiente"); // NOI18N

        jLabelDimensioneRAM.setFont(resourceMap.getFont("jLabelDimensioneRAM.font")); // NOI18N
        jLabelDimensioneRAM.setText(resourceMap.getString("jLabelDimensioneRAM.text")); // NOI18N
        jLabelDimensioneRAM.setName("jLabelDimensioneRAM"); // NOI18N

        jLabelDimensioneSWAP.setFont(resourceMap.getFont("jLabelDimensioneSWAP.font")); // NOI18N
        jLabelDimensioneSWAP.setText(resourceMap.getString("jLabelDimensioneSWAP.text")); // NOI18N
        jLabelDimensioneSWAP.setName("jLabelDimensioneSWAP"); // NOI18N

        jLabelTempoContextSwitch.setFont(resourceMap.getFont("jLabelTempoContextSwitch.font")); // NOI18N
        jLabelTempoContextSwitch.setText(resourceMap.getString("jLabelTempoContextSwitch.text")); // NOI18N
        jLabelTempoContextSwitch.setName("jLabelTempoContextSwitch"); // NOI18N

        jLabelTempoAccessoDisco.setFont(resourceMap.getFont("jLabelTempoAccessoDisco.font")); // NOI18N
        jLabelTempoAccessoDisco.setText(resourceMap.getString("jLabelTempoAccessoDisco.text")); // NOI18N
        jLabelTempoAccessoDisco.setName("jLabelTempoAccessoDisco"); // NOI18N

        jLabelBandaBusDati.setFont(resourceMap.getFont("jLabelBandaBusDati.font")); // NOI18N
        jLabelBandaBusDati.setText(resourceMap.getString("jLabelBandaBusDati.text")); // NOI18N
        jLabelBandaBusDati.setName("jLabelBandaBusDati"); // NOI18N

        jLabelNumProcessi.setFont(resourceMap.getFont("jLabelNumProcessi.font")); // NOI18N
        jLabelNumProcessi.setText(resourceMap.getString("jLabelNumProcessi.text")); // NOI18N
        jLabelNumProcessi.setName("jLabelNumProcessi"); // NOI18N

        jButtonAvanti.setText(resourceMap.getString("jButtonAvanti.text")); // NOI18N
        jButtonAvanti.setName("jButtonAvanti"); // NOI18N
        jButtonAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvantiActionPerformed(evt);
            }
        });

        jButtonAnnulla.setText(resourceMap.getString("jButtonAnnulla.text")); // NOI18N
        jButtonAnnulla.setName("jButtonAnnulla"); // NOI18N
        jButtonAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaActionPerformed(evt);
            }
        });

        jSpinnerProcessi.setName("jSpinnerProcessi"); // NOI18N

        jLabelDimensionePagina.setFont(resourceMap.getFont("jLabelDimensionePagina.font")); // NOI18N
        jLabelDimensionePagina.setText(resourceMap.getString("jLabelDimensionePagina.text")); // NOI18N
        jLabelDimensionePagina.setName("jLabelDimensionePagina"); // NOI18N

        jSpinnerTempoContextSwitch.setName("jSpinnerTempoContextSwitch"); // NOI18N

        jSpinnerTempoAccessoDisco.setName("jSpinnerTempoAccessoDisco"); // NOI18N

        jSpinnerBandaBusDati.setName("jSpinnerBandaBusDati"); // NOI18N

        jSpinnerDimensioneRAM.setName("jSpinnerDimensioneRAM"); // NOI18N

        jSpinnerDimensioneAreaSWAP.setName("jSpinnerDimensioneAreaSWAP"); // NOI18N

        jSpinnerDimensionePagina.setName("jSpinnerDimensionePagina"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitoloConfigurazioneAmbiente, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButtonAvanti))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDimensioneRAM)
                                    .addComponent(jLabelNumProcessi)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTempoContextSwitch)
                                    .addComponent(jLabelTempoAccessoDisco)
                                    .addComponent(jLabelBandaBusDati)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelDimensioneSWAP))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelDimensionePagina)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBandaBusDati, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addComponent(jSpinnerTempoAccessoDisco, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonAnnulla)
                                .addGap(133, 133, 133))
                            .addComponent(jSpinnerProcessi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSpinnerTempoContextSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSpinnerDimensioneAreaSWAP, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSpinnerDimensionePagina, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSpinnerDimensioneRAM, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitoloConfigurazioneAmbiente)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumProcessi)
                    .addComponent(jSpinnerProcessi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDimensioneRAM)
                    .addComponent(jSpinnerDimensioneRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDimensioneAreaSWAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDimensioneSWAP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDimensionePagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDimensionePagina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempoContextSwitch)
                    .addComponent(jSpinnerTempoContextSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempoAccessoDisco)
                    .addComponent(jSpinnerTempoAccessoDisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBandaBusDati)
                    .addComponent(jSpinnerBandaBusDati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAvanti)
                    .addComponent(jButtonAnnulla))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvantiActionPerformed
     
       setNumProcessi(Integer.parseInt(jSpinnerProcessi.getValue().toString()));
       setDimensioneRAM(Integer.parseInt(jSpinnerDimensioneRAM.getValue().toString()));
       setBandaBusDati(Integer.parseInt(jSpinnerBandaBusDati.getValue().toString()));
       setDimensioneAreaSWAP(Integer.parseInt(jSpinnerDimensioneAreaSWAP.getValue().toString()));
       setDimensionePagina(Integer.parseInt(jSpinnerDimensionePagina.getValue().toString()));
       setTempoAccessoDisco(Integer.parseInt(jSpinnerTempoAccessoDisco.getValue().toString()));
       setTempoContextSwitch(Integer.parseInt(jSpinnerTempoContextSwitch.getValue().toString()));

       this.setVisible(false);
       
       PoliticheJDialog politicheJDialog = new PoliticheJDialog(SiGeMv2App.getApplication().getMainFrame(), true, this);
       politicheJDialog.setVisible(true);
    }//GEN-LAST:event_jButtonAvantiActionPerformed

    private void jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButtonAnnullaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonAvanti;
    private javax.swing.JLabel jLabelBandaBusDati;
    private javax.swing.JLabel jLabelDimensionePagina;
    private javax.swing.JLabel jLabelDimensioneRAM;
    private javax.swing.JLabel jLabelDimensioneSWAP;
    private javax.swing.JLabel jLabelNumProcessi;
    private javax.swing.JLabel jLabelTempoAccessoDisco;
    private javax.swing.JLabel jLabelTempoContextSwitch;
    private javax.swing.JLabel jLabelTitoloConfigurazioneAmbiente;
    private javax.swing.JSpinner jSpinnerBandaBusDati;
    private javax.swing.JSpinner jSpinnerDimensioneAreaSWAP;
    private javax.swing.JSpinner jSpinnerDimensionePagina;
    private javax.swing.JSpinner jSpinnerDimensioneRAM;
    private javax.swing.JSpinner jSpinnerProcessi;
    private javax.swing.JSpinner jSpinnerTempoAccessoDisco;
    private javax.swing.JSpinner jSpinnerTempoContextSwitch;
    // End of variables declaration//GEN-END:variables

    private Integer[] impostaNumProcessi() {
        Integer[] numProcessiArray= new Integer[DIMPROCESSI];
        for (int i=0; i<DIMPROCESSI; i++)
            numProcessiArray[i]= (i+1);
        return numProcessiArray;
    }

    private Integer[] impostaDimensioniRAM() {
        Integer[] dimensioniRAM= new Integer[DIMRAM];
        Double potenza;
        for (int i=0; i<DIMRAM; i++) {
            potenza = Math.pow(2,(i+1));
            dimensioniRAM[i] = potenza.intValue();
        }
        return dimensioniRAM;
    }
    
    private Integer[] impostaDimensioniSWAP() {
        Integer[] dimensioniSWAP= new Integer[DIMSWAP];
        Double potenza;
        for (int i=0; i<DIMSWAP; i++) {
            potenza = Math.pow(2,(i+1));
            dimensioniSWAP[i]= potenza.intValue();
        }
        return dimensioniSWAP;
    }

        private Integer[] impostaPagine() {
        Integer[] dimensioniPagine= new Integer[DIMPAGINE];
        Double potenza;
        dimensioniPagine[0]=1;
        for (int i=1; i<DIMPAGINE; i++) {
            potenza = Math.pow(2,i);
            dimensioniPagine[i]= potenza.intValue();
        }
        return dimensioniPagine;
    }

    private Integer[] impostaTempi() {
        Integer[] tempo = new Integer[6];
        tempo[0]=1;
        tempo[1]=5;
        tempo[2]=50;
        tempo[3]=500;
        tempo[4]=1000;
        tempo[5]=2000;
        return tempo;
    }

    private void initJSpinnerProcessi() {
        jSpinnerProcessi.setModel(new SpinnerListModel(impostaNumProcessi()));
    }
    
    private void initSpinnerDimensioneRAM() {
        jSpinnerDimensioneRAM.setModel(new SpinnerListModel(impostaDimensioniRAM()));
    }

    private void initSpinnerDimensioneSWAP() {
        jSpinnerDimensioneAreaSWAP.setModel(new SpinnerListModel(impostaDimensioniSWAP()));
    }
       
    private void initSpinnerPagine() {
        jSpinnerDimensionePagina.setModel(new SpinnerListModel(impostaPagine()));
    }
    
    private void initSpinnerTempi() {
        jSpinnerTempoContextSwitch.setModel(new SpinnerListModel(impostaTempi()));
        jSpinnerTempoAccessoDisco.setModel(new SpinnerListModel(impostaTempi()));
    }
    
    public int getNumProcessi() {
        return numProcessi;
    }

    public void setNumProcessi(int numProcessi) {
        this.numProcessi = numProcessi;
    }    

public int getBandaBusDati() {
        return bandaBusDati;
    }

    public void setBandaBusDati(int bandaBusDati) {
        this.bandaBusDati = bandaBusDati;
    }

    public int getDimensioneAreaSWAP() {
        return dimensioneAreaSWAP;
    }

    public void setDimensioneAreaSWAP(int dimensioneAreaSWAP) {
        this.dimensioneAreaSWAP = dimensioneAreaSWAP;
    }

    public int getDimensionePagina() {
        return dimensionePagina;
    }

    public void setDimensionePagina(int dimensionePagina) {
        this.dimensionePagina = dimensionePagina;
    }

    public int getDimensioneRAM() {
        return dimensioneRAM;
    }

    public void setDimensioneRAM(int dimensioneRAM) {
        this.dimensioneRAM = dimensioneRAM;
    }

    public int getTempoAccessoDisco() {
        return tempoAccessoDisco;
    }

    public void setTempoAccessoDisco(int tempoAccessoDisco) {
        this.tempoAccessoDisco = tempoAccessoDisco;
    }

    public int getTempoContextSwitch() {
        return tempoContextSwitch;
    }

    public void setTempoContextSwitch(int tempoContextSwitch) {
        this.tempoContextSwitch = tempoContextSwitch;
    }
}
