/*
 * Azienda: Stylosoft
 * Nome file: PoliticheJDialog.java
 * Package: gui.dialog
 * Autore: Giordano Cariani
 * Data: 28/02/2008
 * Versione: 1.0
 * Licenza: open-source
 * Registro delle modifiche: *  
 *  - v.1.0 (24/02/2008): Creazione JDialog e impostazione grafica
 */

package gui.dialog;

import gui.SiGeMv2App;
import gui.SiGeMv2View;

/**
 *
 * @author  Jordy
 */
public class PoliticheJDialog extends javax.swing.JDialog {

    private ConfigurazioneAmbienteJDialog configurazioneAmbiente;
    private ProcessiJDialog processi;
    private SiGeMv2View view;
    
    private String politicaPagina;
    private String politicaSegmenti;
    private String politicaSchedulazione;
    
    /** Creates new form PoliticheJDialog */
    public PoliticheJDialog(java.awt.Frame parent, boolean modal, ConfigurazioneAmbienteJDialog conf, SiGeMv2View view) {
        super(parent, modal);
        configurazioneAmbiente = conf;
        this.view = view;
        initComponents();
        setPoliticaPagina((String)jComboBoxRimpiazzoPagine.getItemAt(0));
        setPoliticaSegmenti((String)jComboBoxRimpiazzoSegmenti.getItemAt(0));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitoloPolitiche = new javax.swing.JLabel();
        jLabelRimpiazzoPagine = new javax.swing.JLabel();
        jComboBoxRimpiazzoPagine = new javax.swing.JComboBox();
        jLabelRimpiazzoSegmenti = new javax.swing.JLabel();
        jComboBoxRimpiazzoSegmenti = new javax.swing.JComboBox();
        jButtonIndietro = new javax.swing.JButton();
        jButtonAvanti = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();
        jLabelSchedulazione = new javax.swing.JLabel();
        jComboBoxSchedulazione = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gui.SiGeMv2App.class).getContext().getResourceMap(PoliticheJDialog.class);
        jLabelTitoloPolitiche.setFont(resourceMap.getFont("jLabelTitoloPolitiche.font")); // NOI18N
        jLabelTitoloPolitiche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitoloPolitiche.setText(resourceMap.getString("jLabelTitoloPolitiche.text")); // NOI18N
        jLabelTitoloPolitiche.setName("jLabelTitoloPolitiche"); // NOI18N

        jLabelRimpiazzoPagine.setFont(resourceMap.getFont("jLabelRimpiazzoPagine.font")); // NOI18N
        jLabelRimpiazzoPagine.setText(resourceMap.getString("jLabelRimpiazzoPagine.text")); // NOI18N
        jLabelRimpiazzoPagine.setName("jLabelRimpiazzoPagine"); // NOI18N

        jComboBoxRimpiazzoPagine.setFont(resourceMap.getFont("jComboBoxRimpiazzoPagine.font")); // NOI18N
        jComboBoxRimpiazzoPagine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Recently Used (NRU)", "First In First Out (FIFO)", "Second Chance (SC)", "Clock (C)", "Least Recently Used (LRU)", "Not Frequently Used (NFU)", "Aging (A)" }));
        jComboBoxRimpiazzoPagine.setAutoscrolls(true);
        jComboBoxRimpiazzoPagine.setName("jComboBoxRimpiazzoPagine"); // NOI18N
        jComboBoxRimpiazzoPagine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRimpiazzoPagineActionPerformed(evt);
            }
        });

        jLabelRimpiazzoSegmenti.setFont(resourceMap.getFont("jLabelRimpiazzoSegmenti.font")); // NOI18N
        jLabelRimpiazzoSegmenti.setText(resourceMap.getString("jLabelRimpiazzoSegmenti.text")); // NOI18N
        jLabelRimpiazzoSegmenti.setName("jLabelRimpiazzoSegmenti"); // NOI18N

        jComboBoxRimpiazzoSegmenti.setFont(resourceMap.getFont("jComboBoxRimpiazzoSegmenti.font")); // NOI18N
        jComboBoxRimpiazzoSegmenti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First-Fit", "Next-Fit", "Best-Fit", "Worst-Fit", "Quick-Fit" }));
        jComboBoxRimpiazzoSegmenti.setAutoscrolls(true);
        jComboBoxRimpiazzoSegmenti.setName("jComboBoxRimpiazzoSegmenti"); // NOI18N
        jComboBoxRimpiazzoSegmenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRimpiazzoSegmentiActionPerformed(evt);
            }
        });

        jButtonIndietro.setText(resourceMap.getString("jButtonIndietro.text")); // NOI18N
        jButtonIndietro.setName("jButtonIndietro"); // NOI18N
        jButtonIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndietroActionPerformed(evt);
            }
        });

        jButtonAvanti.setText(resourceMap.getString("jButtonAvanti.text")); // NOI18N
        jButtonAvanti.setName("jButtonAvanti"); // NOI18N
        jButtonAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvantiActionPerformed(evt);
            }
        });

        jButtonAnnulla.setText(resourceMap.getString("jButtonAnnulla.text")); // NOI18N
        jButtonAnnulla.setName("jButtonAnnulla"); // NOI18N
        jButtonAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaActionPerformed(evt);
            }
        });

        jLabelSchedulazione.setFont(resourceMap.getFont("jLabelSchedulazione.font")); // NOI18N
        jLabelSchedulazione.setText(resourceMap.getString("jLabelSchedulazione.text")); // NOI18N
        jLabelSchedulazione.setName("jLabelSchedulazione"); // NOI18N

        jComboBoxSchedulazione.setFont(resourceMap.getFont("jComboBoxSchedulazione.font")); // NOI18N
        jComboBoxSchedulazione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First-Come-First-Served (FCFS)", "Priorità (P)", "Round Robin (RR)", "Round Robin con priorità (RRP)", "Round Robin con priorità e prerilascio (RRPP)", "Shortest Job First (SJF)", "Shortest Remaining Time Next (SRTN)" }));
        jComboBoxSchedulazione.setName("jComboBoxSchedulazione"); // NOI18N
        jComboBoxSchedulazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSchedulazioneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitoloPolitiche, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonIndietro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAvanti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnnulla)
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRimpiazzoPagine)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRimpiazzoSegmenti)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSchedulazione)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSchedulazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxRimpiazzoPagine, 0, 197, Short.MAX_VALUE)
                .addGap(199, 199, 199))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxRimpiazzoSegmenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitoloPolitiche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRimpiazzoPagine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxRimpiazzoPagine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRimpiazzoSegmenti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxRimpiazzoSegmenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabelSchedulazione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxSchedulazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIndietro)
                    .addComponent(jButtonAvanti)
                    .addComponent(jButtonAnnulla))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxRimpiazzoPagineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRimpiazzoPagineActionPerformed
        setPoliticaPagina((String)jComboBoxRimpiazzoPagine.getItemAt(jComboBoxRimpiazzoPagine.getSelectedIndex()));
    }//GEN-LAST:event_jComboBoxRimpiazzoPagineActionPerformed

    private void jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButtonAnnullaActionPerformed

    private void jButtonIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndietroActionPerformed
        this.setVisible(false);
        configurazioneAmbiente.setVisible(true);
    }//GEN-LAST:event_jButtonIndietroActionPerformed

    private void jButtonAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvantiActionPerformed
        this.setVisible(false);
        processi = new ProcessiJDialog(SiGeMv2App.getApplication().getMainFrame(), true, configurazioneAmbiente, this, view);
        processi.setVisible(true);
    }//GEN-LAST:event_jButtonAvantiActionPerformed

    private void jComboBoxRimpiazzoSegmentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRimpiazzoSegmentiActionPerformed
        setPoliticaSegmenti((String)jComboBoxRimpiazzoSegmenti.getItemAt(jComboBoxRimpiazzoSegmenti.getSelectedIndex()));
    }//GEN-LAST:event_jComboBoxRimpiazzoSegmentiActionPerformed

    private void jComboBoxSchedulazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSchedulazioneActionPerformed
        setPoliticaSchedulazione((String)jComboBoxSchedulazione.getItemAt(jComboBoxSchedulazione.getSelectedIndex()));
    }//GEN-LAST:event_jComboBoxSchedulazioneActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonAvanti;
    private javax.swing.JButton jButtonIndietro;
    private javax.swing.JComboBox jComboBoxRimpiazzoPagine;
    private javax.swing.JComboBox jComboBoxRimpiazzoSegmenti;
    private javax.swing.JComboBox jComboBoxSchedulazione;
    private javax.swing.JLabel jLabelRimpiazzoPagine;
    private javax.swing.JLabel jLabelRimpiazzoSegmenti;
    private javax.swing.JLabel jLabelSchedulazione;
    private javax.swing.JLabel jLabelTitoloPolitiche;
    // End of variables declaration//GEN-END:variables

    public String getPoliticaPagina() {
        return politicaPagina;
    }

    public void setPoliticaPagina(String politicaPagina) {
        int inizio = politicaPagina.lastIndexOf("(");
        int fine = politicaPagina.lastIndexOf(")");
        this.politicaPagina = politicaPagina.substring(inizio+1, fine);
    }

    public String getPoliticaSegmenti() {
        return politicaSegmenti;
    }

    public void setPoliticaSegmenti(String politicaSegmenti) {
        this.politicaSegmenti = politicaSegmenti;
    }

    public String getPoliticaSchedulazione() {
        return politicaSchedulazione;
    }

    public void setPoliticaSchedulazione(String politicaSchedulazione) {
        int inizio = politicaSchedulazione.lastIndexOf("(");
        int fine = politicaSchedulazione.lastIndexOf(")");
        this.politicaSchedulazione = politicaSchedulazione.substring(inizio+1, fine);
    }
}
