/*
 * Azienda: Stylosoft
 * Nome file: PoliticheJDialog.java
 * Package: gui.dialog
 * Autore: Giordano Cariani
 * Data: 25/03/2008
 * Versione: 1.3
 * Licenza: open-source
 * Registro delle modifiche: 
 *  - v.1.3 (25/03/2008): Inserito bottone help
 *  - v.1.2 (15/03/2008): Inserita gestione modifica configurazione
 *  - v.1.1 (02/03/2008): migliorata la gestione delle variabili private
 *                        inserita label "passo 2 di 4"
 *  - v.1.0 (01/03/2008): Creazione JDialog e impostazione grafica
 */

package gui.dialog;
import gui.SiGeMv2View;
import gui.utility.HelpHtml;
import javax.swing.SpinnerListModel;
import logic.parametri.ConfigurazioneIniziale;
/**
 *
 * @author  Giordano Cariani
 */
public class PoliticheJDialog extends javax.swing.JDialog {
    
    private ConfigurazioneAmbienteJDialog configurazioneAmbiente;
    private ProcessiJDialog processi;
    private ConfigurazioneIniziale confIniziale;
    private SiGeMv2View view;
    
    private int gestioneMemoria;
    private int politica;
    private int politicaSchedulazione;
    private int timeSlice;
    
    boolean modifica = false;
    
    /** Crea il form PoliticheJDialog */
    public PoliticheJDialog(java.awt.Frame parent, boolean modal, ConfigurazioneAmbienteJDialog conf, SiGeMv2View view) {
        super(parent, modal);
        configurazioneAmbiente = conf;
        this.view = view;
        initComponents();
        initJSpinnerTimeSlice();
        jLabelTimeSlice.setVisible(false);
        jSpinnerTimeSlice.setVisible(false);
        setTimeSlice(0);
        gestionePoliticaPagine((String)jComboBoxRimpiazzoPagine.getItemAt(0));
        gestioneSchedulazione((String) jComboBoxSchedulazione.getItemAt(0));
        jComboBoxRimpiazzoSegmenti.setEnabled(false);
    }
    
   public PoliticheJDialog(java.awt.Frame parent, boolean modal, ConfigurazioneAmbienteJDialog conf, SiGeMv2View view,
           ConfigurazioneIniziale confIniziale) {
        super(parent, modal);
        configurazioneAmbiente = conf;
        this.view = view;
        setGestioneMemoria(confIniziale.getModalitaGestioneMemoria());
        setPolitica(confIniziale.getPoliticaGestioneMemoria());
        setPoliticaSchedulazione(confIniziale.getPoliticaSchedulazioneProcessi());
        setTimeSlice(confIniziale.getTimeSlice());
        initComponents();
        initJSpinnerTimeSlice();
        impostaSpinnerTimeSlice();
        if (politicaSchedulazione == 4
        ||  politicaSchedulazione == 5
        ||  politicaSchedulazione == 6) {
            jLabelTimeSlice.setVisible(true);
            jSpinnerTimeSlice.setVisible(true);
        } else {
            jLabelTimeSlice.setVisible(false);
            jSpinnerTimeSlice.setVisible(false);
        }

        jComboBoxSuddivisioneMemoria.setSelectedIndex(getGestioneMemoria()-1);
        if (getGestioneMemoria() == 1) {
           jComboBoxRimpiazzoSegmenti.setEnabled(false);
           jComboBoxRimpiazzoPagine.setEnabled(true);
           gestionePoliticaPagineMod();
        } else if (getGestioneMemoria() == 2){
           jComboBoxRimpiazzoPagine.setEnabled(false);
           jComboBoxRimpiazzoSegmenti.setEnabled(true);
           gestionePoliticaSegmentiMod();
        }

        gestionePoliticaSchedulazioneMod();
        this.confIniziale = confIniziale;
        modifica=true;
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPolitiche = new javax.swing.JLabel();
        jLabelRimpiazzoPagine = new javax.swing.JLabel();
        jComboBoxRimpiazzoPagine = new javax.swing.JComboBox();
        jLabelRimpiazzoSegmenti = new javax.swing.JLabel();
        jComboBoxRimpiazzoSegmenti = new javax.swing.JComboBox();
        jLabelSchedulazione = new javax.swing.JLabel();
        jComboBoxSchedulazione = new javax.swing.JComboBox();
        jButtonIndietro = new javax.swing.JButton();
        jButtonAvanti = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();
        jLabelTecnicaGestioneMemoria = new javax.swing.JLabel();
        jComboBoxSuddivisioneMemoria = new javax.swing.JComboBox();
        jLabelPasso = new javax.swing.JLabel();
        jLabelTimeSlice = new javax.swing.JLabel();
        jSpinnerTimeSlice = new javax.swing.JSpinner();
        jButtonHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPolitiche.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabelPolitiche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPolitiche.setText("POLITICHE");

        jLabelRimpiazzoPagine.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelRimpiazzoPagine.setText("Politica di rimpiazzo delle pagine");

        jComboBoxRimpiazzoPagine.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxRimpiazzoPagine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Recently Used (NRU)", "First In First Out (FIFO)", "Second Chance (SC)", "Clock (C)", "Least Recently Used (LRU)", "Not Frequently Used (NFU)", "Aging (A)" }));
        jComboBoxRimpiazzoPagine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRimpiazzoPagineActionPerformed(evt);
            }
        });

        jLabelRimpiazzoSegmenti.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelRimpiazzoSegmenti.setText("Politica di allocazione dei segmenti");

        jComboBoxRimpiazzoSegmenti.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxRimpiazzoSegmenti.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First-Fit", "Next-Fit", "Best-Fit", "Worst-Fit", "Quick-Fit" }));
        jComboBoxRimpiazzoSegmenti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRimpiazzoSegmentiActionPerformed(evt);
            }
        });

        jLabelSchedulazione.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelSchedulazione.setText("Politica di schedulazione");

        jComboBoxSchedulazione.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxSchedulazione.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "First-Come-First-Served (FCFS)", "Shortest Job First (SJF)", "Shortest Remaining Time Next (SRTN)", "Round Robin (RR)", "Round Robin con priorità (RRP)", "Round Robin con priorità e prerilascio (RRPP)", "Priorità (P)" }));
        jComboBoxSchedulazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSchedulazioneActionPerformed(evt);
            }
        });

        jButtonIndietro.setText("Indietro");
        jButtonIndietro.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonIndietro.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonIndietro.setPreferredSize(new java.awt.Dimension(72, 23));
        jButtonIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndietroActionPerformed(evt);
            }
        });

        jButtonAvanti.setText("Avanti");
        jButtonAvanti.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonAvanti.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonAvanti.setPreferredSize(new java.awt.Dimension(72, 23));
        jButtonAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvantiActionPerformed(evt);
            }
        });

        jButtonAnnulla.setText("Annulla");
        jButtonAnnulla.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonAnnulla.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonAnnulla.setPreferredSize(new java.awt.Dimension(72, 23));
        jButtonAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaActionPerformed(evt);
            }
        });

        jLabelTecnicaGestioneMemoria.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelTecnicaGestioneMemoria.setText("Tecnica di gestione memoria");

        jComboBoxSuddivisioneMemoria.setFont(new java.awt.Font("Tahoma", 0, 12));
        jComboBoxSuddivisioneMemoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pagine", "segmenti" }));
        jComboBoxSuddivisioneMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSuddivisioneMemoriaActionPerformed(evt);
            }
        });

        jLabelPasso.setFont(new java.awt.Font("Tahoma", 0, 10));
        jLabelPasso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPasso.setText("Passo 2 di 4");

        jLabelTimeSlice.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabelTimeSlice.setText("Time Slice");

        jButtonHelp.setText("Help");
        jButtonHelp.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonHelp.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonHelp.setPreferredSize(new java.awt.Dimension(72, 23));
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPolitiche, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(jLabelPasso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelTimeSlice)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBoxSchedulazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinnerTimeSlice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelSchedulazione)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelRimpiazzoSegmenti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRimpiazzoPagine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTecnicaGestioneMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxSuddivisioneMemoria, 0, 180, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRimpiazzoPagine, 0, 180, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRimpiazzoSegmenti, javax.swing.GroupLayout.Alignment.LEADING, 0, 180, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPasso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPolitiche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSuddivisioneMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTecnicaGestioneMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRimpiazzoPagine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRimpiazzoPagine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRimpiazzoSegmenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRimpiazzoSegmenti))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSchedulazione)
                    .addComponent(jLabelTimeSlice, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSchedulazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTimeSlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAvanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAnnulla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIndietro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndietroActionPerformed
        this.setVisible(false);
        configurazioneAmbiente.setVisible(true);
}//GEN-LAST:event_jButtonIndietroActionPerformed

    private void jButtonAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvantiActionPerformed
        setTimeSlice(Integer.parseInt(jSpinnerTimeSlice.getValue().toString()));
        this.setVisible(false);
        if (modifica)
            processi = new ProcessiJDialog(view.getFrame(), true, configurazioneAmbiente, this, view, confIniziale);
        else
            processi = new ProcessiJDialog(view.getFrame(), true, configurazioneAmbiente, this, view);
        processi.setVisible(true);
    }//GEN-LAST:event_jButtonAvantiActionPerformed

    private void jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAnnullaActionPerformed

    private void jComboBoxRimpiazzoPagineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRimpiazzoPagineActionPerformed
        gestionePoliticaPagine((String)jComboBoxRimpiazzoPagine.getItemAt(jComboBoxRimpiazzoPagine.getSelectedIndex()));
    }//GEN-LAST:event_jComboBoxRimpiazzoPagineActionPerformed

    private void jComboBoxRimpiazzoSegmentiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRimpiazzoSegmentiActionPerformed
        gestionePoliticaSegmenti((String)jComboBoxRimpiazzoSegmenti.getItemAt(jComboBoxRimpiazzoSegmenti.getSelectedIndex()));
    }//GEN-LAST:event_jComboBoxRimpiazzoSegmentiActionPerformed

    private void jComboBoxSchedulazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSchedulazioneActionPerformed
        gestioneSchedulazione((String)jComboBoxSchedulazione.getItemAt(jComboBoxSchedulazione.getSelectedIndex()));
        // visualizzo il time slice in caso di RR
        if (politicaSchedulazione == 4
        ||  politicaSchedulazione == 5
        ||  politicaSchedulazione == 6) {
            jLabelTimeSlice.setVisible(true);
            jSpinnerTimeSlice.setVisible(true);
        } else {
            jLabelTimeSlice.setVisible(false);
            jSpinnerTimeSlice.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxSchedulazioneActionPerformed

    private void jComboBoxSuddivisioneMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSuddivisioneMemoriaActionPerformed
       if ("pagine".equalsIgnoreCase((String) jComboBoxSuddivisioneMemoria.getItemAt(jComboBoxSuddivisioneMemoria.getSelectedIndex()))) {
           setGestioneMemoria(1);
           jComboBoxRimpiazzoSegmenti.setEnabled(false);
           jComboBoxRimpiazzoPagine.setEnabled(true);
       }
       else if ("segmenti".equalsIgnoreCase((String) jComboBoxSuddivisioneMemoria.getItemAt(jComboBoxSuddivisioneMemoria.getSelectedIndex()))) {
           setGestioneMemoria(2);
           jComboBoxRimpiazzoPagine.setEnabled(false);
           jComboBoxRimpiazzoSegmenti.setEnabled(true);
       }
    }//GEN-LAST:event_jComboBoxSuddivisioneMemoriaActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        HelpHtml.openUrl("pagina.htm#Passo2");
    }//GEN-LAST:event_jButtonHelpActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonAvanti;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JButton jButtonIndietro;
    private javax.swing.JComboBox jComboBoxRimpiazzoPagine;
    private javax.swing.JComboBox jComboBoxRimpiazzoSegmenti;
    private javax.swing.JComboBox jComboBoxSchedulazione;
    private javax.swing.JComboBox jComboBoxSuddivisioneMemoria;
    private javax.swing.JLabel jLabelPasso;
    private javax.swing.JLabel jLabelPolitiche;
    private javax.swing.JLabel jLabelRimpiazzoPagine;
    private javax.swing.JLabel jLabelRimpiazzoSegmenti;
    private javax.swing.JLabel jLabelSchedulazione;
    private javax.swing.JLabel jLabelTecnicaGestioneMemoria;
    private javax.swing.JLabel jLabelTimeSlice;
    private javax.swing.JSpinner jSpinnerTimeSlice;
    // End of variables declaration//GEN-END:variables

    public int getGestioneMemoria() {
        return gestioneMemoria;
    }

    public void setGestioneMemoria(int gestioneMemoria) {
        this.gestioneMemoria = gestioneMemoria;
    }

    public int getPolitica() {
        return politica;
    }

    public void setPolitica(int politica) {
        this.politica = politica;
    }

    public int getPoliticaSchedulazione() {
        return politicaSchedulazione;
    }

    public void setPoliticaSchedulazione(int politicaSchedulazione) {
        this.politicaSchedulazione = politicaSchedulazione;
    }

    private void gestionePoliticaPagine(String politica) {
        int inizio = politica.lastIndexOf("(");
        int fine = politica.lastIndexOf(")");
        politica = politica.substring(inizio+1, fine);
        setGestioneMemoria(1);
        if (politica.equalsIgnoreCase("NRU"))
            setPolitica(1);
        else if (politica.equalsIgnoreCase("FIFO"))
            setPolitica(2);
        else if (politica.equalsIgnoreCase("SC"))
            setPolitica(3);
        else if (politica.equalsIgnoreCase("C"))
            setPolitica(4);
        else if (politica.equalsIgnoreCase("LRU"))
            setPolitica(5);
        else if (politica.equalsIgnoreCase("NFU"))
            setPolitica(6);
        else if (politica.equalsIgnoreCase("A"))
            setPolitica(7);
    }
     
    private void gestionePoliticaSegmenti(String politica) {
        setGestioneMemoria(2);
        if (politica.equalsIgnoreCase("FIRST-FIT"))
            setPolitica(1);
        else if (politica.equalsIgnoreCase("NEXT-FIT"))
            setPolitica(2);
        else if (politica.equalsIgnoreCase("BEST-FIT"))
            setPolitica(3);
        else if (politica.equalsIgnoreCase("WORKS-FIT"))
            setPolitica(4);
        else if (politica.equalsIgnoreCase("QUICK-FIT"))
            setPolitica(5);
        }
    
    private void gestioneSchedulazione(String politica) {
        int inizio = politica.lastIndexOf("(");
        int fine = politica.lastIndexOf(")");
        politica = politica.substring(inizio+1, fine);
        if (politica.equalsIgnoreCase("FCFS"))
            setPoliticaSchedulazione(1);
        else if (politica.equalsIgnoreCase("SJF"))
            setPoliticaSchedulazione(2);
        else if (politica.equalsIgnoreCase("SRTN"))
            setPoliticaSchedulazione(3);
        else if (politica.equalsIgnoreCase("RR"))
            setPoliticaSchedulazione(4);
        else if (politica.equalsIgnoreCase("RRP"))
            setPoliticaSchedulazione(5);
        else if (politica.equalsIgnoreCase("RRPP"))
            setPoliticaSchedulazione(6);
        else if (politica.equalsIgnoreCase("P"))
            setPoliticaSchedulazione(7);
    }
    
    private Integer[] impostaJSpinnerTimeSlice() {
        Integer[] tempiTimeSlice= new Integer[9];
        tempiTimeSlice[0]=2;
        for (int i=1; i<9; i++)
            tempiTimeSlice[i] = i+2;
        return tempiTimeSlice;
    }
   
    private void initJSpinnerTimeSlice() {
        jSpinnerTimeSlice.setModel(new SpinnerListModel(impostaJSpinnerTimeSlice()));
    }
    
    private void impostaSpinnerTimeSlice() {
        jSpinnerTimeSlice.setValue(getTimeSlice());
    }
    
    private void gestionePoliticaPagineMod() {
        jComboBoxRimpiazzoPagine.setSelectedIndex(getPolitica()-1);
    }

    private void gestionePoliticaSegmentiMod() {
        jComboBoxRimpiazzoSegmenti.setSelectedIndex(getPolitica()-1);
    }
    
    private void gestionePoliticaSchedulazioneMod() {
        jComboBoxSchedulazione.setSelectedIndex(getPoliticaSchedulazione()  -1);
    }
    
    public int getTimeSlice() {
        return timeSlice;
    }

    public void setTimeSlice(int timeSlice) {
        this.timeSlice = timeSlice;
    }
    
}
