/*
 * ProcessiJDialog.java
 *
 * Created on 24 febbraio 2008, 16.08
 */

package gui.dialog;

import gui.SiGeMv2App;
import gui.SiGeMv2View;

/**
 *
 * @author  Jordy
 */
public class ProcessiJDialog extends javax.swing.JDialog {
    private ConfigurazioneAmbienteJDialog configurazioneAmbiente;
    private PoliticheJDialog politiche;
    private AssociazioneProcessiJDialog associazioneProcessi;
    private SiGeMv2View view;
    
    private Object[][] combinazioneProcessi;
   
    /** Creates new form ProcessiJDialog */
    public ProcessiJDialog(java.awt.Frame parent, boolean modal, ConfigurazioneAmbienteJDialog conf, PoliticheJDialog pol, SiGeMv2View view) {
        super(parent, modal);
        configurazioneAmbiente = conf;
        politiche = pol;
        this.view = view;
        initComponents();
        initTable(); 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelParametriProcessi = new javax.swing.JLabel();
        jButtonIndietro = new javax.swing.JButton();
        jButtonAvanti = new javax.swing.JButton();
        jButtonAnnulla = new javax.swing.JButton();
        jScrollPaneProcessi = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(gui.SiGeMv2App.class).getContext().getResourceMap(ProcessiJDialog.class);
        jLabelParametriProcessi.setFont(resourceMap.getFont("jLabelParametriProcessi.font")); // NOI18N
        jLabelParametriProcessi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelParametriProcessi.setText(resourceMap.getString("jLabelParametriProcessi.text")); // NOI18N
        jLabelParametriProcessi.setName("jLabelParametriProcessi"); // NOI18N

        jButtonIndietro.setText(resourceMap.getString("jButtonIndietro.text")); // NOI18N
        jButtonIndietro.setName("jButtonIndietro"); // NOI18N
        jButtonIndietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndietroActionPerformed(evt);
            }
        });

        jButtonAvanti.setText(resourceMap.getString("jButtonAvanti.text")); // NOI18N
        jButtonAvanti.setName("jButtonAvanti"); // NOI18N
        jButtonAvanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvantiActionPerformed(evt);
            }
        });

        jButtonAnnulla.setText(resourceMap.getString("jButtonAnnulla.text")); // NOI18N
        jButtonAnnulla.setName("jButtonAnnulla"); // NOI18N
        jButtonAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnullaActionPerformed(evt);
            }
        });

        jScrollPaneProcessi.setName("jScrollPaneProcessi"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneProcessi, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addComponent(jLabelParametriProcessi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButtonIndietro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAvanti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnnulla)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelParametriProcessi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneProcessi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIndietro)
                    .addComponent(jButtonAvanti)
                    .addComponent(jButtonAnnulla))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTable() {      
        
        jTableProcessi = new javax.swing.JTable(new ModelloProcessi(configurazioneAmbiente.getNumProcessi()));
        
        jTableProcessi.setName("jTableProcessi"); // NOI18N
        jScrollPaneProcessi.setViewportView(jTableProcessi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelParametriProcessi, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneProcessi, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButtonIndietro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAvanti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnnulla)))
                .addContainerGap())
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelParametriProcessi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneProcessi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIndietro)
                    .addComponent(jButtonAvanti)
                    .addComponent(jButtonAnnulla))
                .addContainerGap()));
        pack();
         
    }
    private void jButtonIndietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndietroActionPerformed
        this.setVisible(false);
        politiche.setVisible(true);
    }//GEN-LAST:event_jButtonIndietroActionPerformed

    private void jButtonAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnullaActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButtonAnnullaActionPerformed

    private void jButtonAvantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvantiActionPerformed
        combinazioneProcessi = new Object[jTableProcessi.getRowCount()][jTableProcessi.getColumnCount()];
        
        for (int row=0; row<jTableProcessi.getRowCount(); row++) 
            for (int col=0; col<jTableProcessi.getColumnCount(); col++)
                combinazioneProcessi[row][col]= jTableProcessi.getValueAt(row, col);
                                    
        this.setVisible(false);
        associazioneProcessi = new AssociazioneProcessiJDialog(SiGeMv2App.getApplication().getMainFrame(), true, configurazioneAmbiente, politiche, this, view);
        associazioneProcessi.setVisible(true);
    }//GEN-LAST:event_jButtonAvantiActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulla;
    private javax.swing.JButton jButtonAvanti;
    private javax.swing.JButton jButtonIndietro;
    private javax.swing.JLabel jLabelParametriProcessi;
    private javax.swing.JScrollPane jScrollPaneProcessi;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JTable jTableProcessi;

    public Object[][] getCombinazioneProcessi() {
        return combinazioneProcessi;
    }

    public void setCombinazioneProcessi(Object[][] combinazioneProcessi) {
        this.combinazioneProcessi = combinazioneProcessi;
    }
}
