# Azienda: Stylosoft

# Nome file: Makefile
# Autore: Alberto Zatton
# Data: 30/03/2008
# Versione: 1.0
# Licenza: open-source
# Registro delle modifiche:
# v.1.0 (30/03/2008): Inserito il comando esegui



esegui:
	java -jar Sigem.jar



